### ISSUE TITLE
Issues with make install-dependencies

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#92] opened 2016-09-16 14:06 UTC
Please note any issues you have with the `make install-dependencies` target here

@AHuelskamp @emilydolson

**Comment by emilydolson** [comment] 2016-09-16 14:11
I just confirmed that I do need to run it with sudo. If I don't, it finishes building Doxygen, and then this happens:

> python -m virtualenv env
> Using base prefix '/home/emily/anaconda3'
> New python executable in env/bin/python
> Installing setuptools, pip, wheel...
>   Complete output from command /home/emily/repos/em...party/env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
>   Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/__init__.py", line 17, in <module>
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/commands/__init__.py", line 6, in <module>
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/commands/completion.py", line 4, in <module>
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 20, in <module>
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/req/__init__.py", line 3, in <module>
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/req/req_install.py", line 17, in <module>
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/_vendor/distlib/markers.py", line 20, in <module>
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/_vendor/distlib/markers.py", line 48, in Evaluator
>   File "/home/emily/anaconda3/lib/python3.4/platform.py", line 1274, in python_implementation
>     return _sys_version()[0]
>   File "/home/emily/anaconda3/lib/python3.4/platform.py", line 1237, in _sys_version
>     repr(sys_version))
> ValueError: failed to parse CPython sys.version: '3.4.3 (default, Oct 14 2015, 20:31:36) \n[GCC 4.8.4]'
> ----------------------------------------
> ...Installing setuptools, pip, wheel...done.
> Traceback (most recent call last):
>   File "/home/emily/anaconda3/lib/python3.4/runpy.py", line 170, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/emily/anaconda3/lib/python3.4/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv.py", line 2363, in <module>
>     main()
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv.py", line 832, in main
>     symlink=options.symlink)
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv.py", line 1004, in create_environment
>     install_wheel(to_install, py_executable, search_dirs)
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv.py", line 969, in install_wheel
>     'PIP_NO_INDEX': '1'
>   File "/home/emily/anaconda3/lib/python3.4/site-packages/virtualenv.py", line 910, in call_subprocess
>     % (cmd_desc, proc.returncode))
> OSError: Command /home/emily/repos/em...party/env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
> make[1]: *** [prepare-virtualenv] Error 1
> make[1]: Leaving directory `/home/emily/repos/empirical_doc_test/third-party'
> make: *** [install-dependencies] Error 2
> 

I'm on Linux Mint 17. It's possible this is specific to my system (I often need to run pip with sudo - I think the permissions on my site-packages directory might be weird).

**Comment by bocajnotnef** [comment] 2016-09-16 14:25
It looks like it may be an issue with using Anaconda python instead of the system Python, according to my testing--though, my failure message is different than yours.

The site package permissions thing definitely could be breaking stuff as well--that dir should be normally writable. The install-dependencies call is designed not to require sudo (for things like running on a VPS, etc.)

A chunk of the issues could probably be resolved by switching to downloading a compiled doxygen instead of compiling it; I don't actually remember if there was a good reason to compile it instead of using the binary, so I'll run a pilot test on that.

**Comment by AHuelskamp** [comment] 2016-09-16 14:28
Running `make install-dependencies` on MacOS 10.10.5 looks like it builds doxygen and then and then fails after that as virtualenv isn't installed.

**Comment by bocajnotnef** [comment] 2016-09-16 14:29
For that, I refer you to item 5 of the one-time prep docs https://empirical.readthedocs.io/en/latest/dev/getting-started.html#one-time-preparation

**Comment by bocajnotnef** [comment] 2016-09-16 14:30
(that said, that assumes you have whatever makes brew go installed, and I have no idea what/how that is.)

**Comment by AHuelskamp** [comment] 2016-09-16 14:32
Running `pip install virtualenv` appears to get past this and successfully goes through `make install-dependencies`. (Looks like I missed RFTMing)

**Comment by bocajnotnef** [comment] 2016-09-16 14:33
to be fair, the link to the docs just hit the repo; wasn't overly visible prior to 10min ago. (now the link is on the README on the repo's main page, muwahahah)

**Comment by AHuelskamp** [comment] 2016-09-16 14:33
Also, I remember having to install cmake yesterday (`brew install cmake` assuming you have brew installed). Didn't see that in the docs yet.

**Comment by bocajnotnef** [comment] 2016-09-16 14:35
I'll add that in!

**Comment by AHuelskamp** [comment] 2016-09-16 14:40
Okay, running `make doc` fails with the following: 
```
cd doc && make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.6
making output directory...
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.

Extension error:
Could not import extension breathe (exception: No module named breathe)
make[1]: *** [html] Error 1
make: *** [doc] Error 2
```
in `third-party/` there's no `breathe` directory but manually running `bash install_breathe.sh` seems to work.

**Comment by AHuelskamp** [comment] 2016-09-16 14:40
*`download_breathe.sh`

**Comment by bocajnotnef** [comment] 2016-09-16 14:43
Hmm. That sounds like an issue with submodules not initializing, but there's commands to do that in the `install-dependencies` target... Weird.

**Comment by bocajnotnef** [comment] 2016-09-16 14:43
Actually it should get installed when installing the pip dependencies, alongside sphinx

**Comment by bocajnotnef** [comment] 2016-09-16 14:44
Which, now that I think about it, means it wouldn't make a breathe/ folder and would shove it in the virtualenv site packages.

the `download_breathe.sh` script is deprecated and needs to be nuked.

Did you `source activate virtualenv_name_here/bin/activate` before `make doc`?

**Comment by AHuelskamp** [comment] 2016-09-16 14:45
No, I'll nuke the breathe/ directory and try running that before `make doc`.

**Comment by AHuelskamp** [comment] 2016-09-16 14:53
Running `source third-party/env/bin/activate` and then `make doc` appears to work 😄 ! I'll nuke everything later today and re-build everything with the newly released docs and note any other issues.

**Comment by bocajnotnef** [comment] 2016-09-16 15:08
Cool! let me know if there are more broken things--I haven't actually gotten a chance to sit down with someone who has OS X to troubleshoot issues with them, so there's probably a lotta broken stuff.

**Comment by emilydolson** [comment] 2020-05-26 22:30
This looks like it's all resolved, so I'm going to go ahead and close this and we can make new issues if we discover new bugs

**Closed by emilydolson** 2020-05-26 22:30 UTC
