### ISSUE TITLE
Weird error when constructing random number generator and world

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#91] opened 2016-09-14 19:59 UTC
Building a random number generator (emp::Random) without passing it an argument (i.e. letting it use the default) and then passing that random number generator into a world constructor throws a weird type error.

**Comment by mercere99** [comment] 2016-09-15 01:43
I can't reproduce this error... can you give example code?  Take a look in examples/evo/ where some of the examples are done this way (such as World.cc).

**Comment by emilydolson** [comment] 2016-09-15 04:13
It was on Sarah's computer. I'll see if I can reproduce it on mine tomorrow.

**Comment by mercere99** [comment] 2017-07-19 13:44
@emilydolson Have you been able to reproduce this error?  If not my inclination is to close this issue.

**Closed** 2017-08-17 01:12 UTC
Labels: Goal: Bug Fix, Removed: Invalid, Topic: Core Tools
